spring.application.name=sansaweigh
spring.mongodb.uri=mongodb://localhost:27017/sansaweigh
spring.data.redis.host=localhost
spring.data.redis.port=6379
external.scale.url=http://localhost:9090/scales
